<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rpg_modeling" nsURI="http://www.example.org/rpg_modeling" nsPrefix="rpg_modeling">
  <eClassifiers xsi:type="ecore:EClass" name="NonPlayerCharacter" eSuperTypes="#//Character"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Grades">
    <eLiterals name="MASTER"/>
    <eLiterals name="OFFICER" value="1"/>
    <eLiterals name="MEMBER" value="2"/>
    <eLiterals name="INTIATE" value="3"/>
    <eLiterals name="NO_MEMBER" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wizard" eSuperTypes="#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="Archer" eSuperTypes="#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equipment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="1"
        eType="#//Character" eOpposite="#//Character/equipment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inventory" lowerBound="1"
        eType="#//PlayerInventory" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="armor" lowerBound="1" eType="#//PlayerArmor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlayerArmor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="equipmentobject" upperBound="8"
        eType="#//EquipmentObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="head" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chest" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assassin" eSuperTypes="#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="Player" eSuperTypes="#//Character">
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" lowerBound="1" eType="#//Class"
        eOpposite="#//Class/player"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guild" eType="#//Guild"
        eOpposite="#//Guild/player"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//Grades"
        defaultValueLiteral="NO_MEMBER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Warrior" eSuperTypes="#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="Class" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="1"
        eType="#//Player" eOpposite="#//Player/class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guild">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guildinventory" lowerBound="1"
        eType="#//GuildInventory" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" upperBound="-1"
        eType="#//Player" eOpposite="#//Player/guild"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Faction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guild" upperBound="-1"
        eType="#//Guild" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquipmentObject" eSuperTypes="#//GameObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CategoryObject"
        defaultValueLiteral="DEFAULT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlayerInventory" eSuperTypes="#//Inventory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="consumableobject" upperBound="-1"
        eType="#//ConsumableObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="questobject" upperBound="-1"
        eType="#//QuestObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="equipmentobject" upperBound="-1"
        eType="#//EquipmentObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Character" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="equipment" lowerBound="1"
        eType="#//Equipment" eOpposite="#//Equipment/player"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuestObject" eSuperTypes="#//GameObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_idQuest" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConsumableObject" eSuperTypes="#//GameObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeEffect" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="#//TypeObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuildInventory" eSuperTypes="#//Inventory"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inventory" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="CategoryObject">
    <eLiterals name="HEAD"/>
    <eLiterals name="ARM" value="1"/>
    <eLiterals name="CHEST" value="2"/>
    <eLiterals name="LEG" value="3"/>
    <eLiterals name="RIGHT_HAND" value="4"/>
    <eLiterals name="LEFT_HAND" value="5"/>
    <eLiterals name="HAND" value="6"/>
    <eLiterals name="FOOT" value="7"/>
    <eLiterals name="DEFAULT" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeObject">
    <eLiterals name="HEAL"/>
    <eLiterals name="POISON" value="1"/>
    <eLiterals name="THUNDER" value="3"/>
    <eLiterals name="DEFAULT" value="8"/>
  </eClassifiers>
</ecore:EPackage>
